version: "3"

services:
  db:
    image: mongo
    command: mongod --port 8333
    ports: 
      - "8333:8333"
    container_name: mongo-backend-docker
  frontend:
    image: agroshop_frontend
    build: ./frontend
    ports: 
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
    depends_on: 
        - db
    container_name: frontend-docker
  backend:
    image: agroshop_backend
    build: ./backend
    ports: 
        - "80:80"
    volumes:
        - ./frontend:/frontend
    depends_on: 
        - db
        - frontend
    container_name: backend-docker
